"use client"
import Head from 'next/head'
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";
import {NextUIProvider} from "@nextui-org/react";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Moge!",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <link href="https://fonts.cdnfonts.com/css/valverde?styles=137784,137785" rel="stylesheet"></link>
      </Head>
      <body>
      <NextUIProvider>
        <Header />
          {children}
        <Footer />
        </NextUIProvider>
      </body>
    </html>
  );
}
