"use client"
import Head from 'next/head'
import { Inter } from "next/font/google";
import AuthContextProvider from '@/contexts/AuthContext';
import "../globals.css";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";
import {NextUIProvider} from "@nextui-org/react";


// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Moge!",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <meta name="csrf-token" content="{{ csrf_token() }}"></meta> */}
      <body>
        
        <AuthContextProvider>
          <Header />
          {children}
          <Footer />
        </AuthContextProvider>
        
      </body>
    </html>
  );
}
