"use client"
import "../app/globals.css";
import Header from "./components/Header/Header.jsx";
import Footer from "./components/Footer/Footer.jsx";
import {NextUIProvider} from "@nextui-org/react";
import AuthContextProvider  from "../contexts/AuthContext";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Moge!",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta name="csrf-token" content="{{ csrf_token() }}"></meta>
      <body>
        
        <AuthContextProvider>
          <Header />
          {children}
          <Footer />
        </AuthContextProvider>
        
      </body>
    </html>
  );
}
